name: staging deployment 
on: 
   push:
     branches: [main]

jobs:
  redeploy_frontend_http_ws_server:
    runs-on: ubuntu-latest
    name: Deploying the frontend to staging cluster

    steps:
      - run:  |
          echo "ready for cicd process"
          echo "${{ toJSON(secrets) }}"
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/SSH_KEY 
          ls
          ls -a
          echo "ready to connect to server"
          ssh -i ~/SSH_KEY root@13.203.159.74 
          cd monorepo_deploymend_cicd && git pull
          pnpm install
          pnpm run build
          pm2 restart http-server
          pm2 restart web
          pm2 restart ws-server 
