name: staging deployment 
on: 
   push:
     branches: [main]

jobs:
  redeploy_frontend_http_ws_server:
    runs-on: ubuntu-latest
    name: Deploying the frontend to staging cluster

    steps:
      - name: Disable SSH Host Key Checking
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - run:  |
          echo "ready for cicd process"
          echo "${{ toJSON(secrets) }}"
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "${{ secrets.SSH_SECRET_KEY }}" | tr -d '\r' > ~/SSH_KEY
          chmod 600 ~/SSH_KEY
          ls
          ls -a
          echo "ready to connect to server"
          ssh -i ~/SSH_KEY ubuntu@13.234.35.28 << 'EOF'
            cd monorepo_deploymend_cicd
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v23.10.0
            nvm use v23.10.0
            npm i -g pm2
            npm i -g pnpm
            git pull
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart web
            pm2 restart ws-server
          EOF
